load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

licenses(["notice"])

package(default_visibility = ["//:__subpackages__"])

swift_library(
    name = "module_cache_pruner_lib",
    srcs = glob(["*.swift"]),
    module_name = "ModuleCachePruner",
)
