name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos_latest:
    name: macos_latest
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: latest
      name: macos_latest
  macos_last_green:
    name: macos_last_green
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: last_green
      name: macos_last_green
  macos_latest_head_deps:
    name: macos_latest_head_deps
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: latest
      name: macos_latest_head_deps
      shell_commands: .bazelci/update_workspace_to_deps_heads.sh
