name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos_rolling:
    name: macos_rolling
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: rolling
      name: macos_rolling
  macos_last_green:
    name: macos_last_green
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: last_green
      name: macos_last_green
  macos_rolling_head_deps:
    name: macos_rolling_head_deps
    uses: bazelbuild/tulsi/.github/workflows/macos.yml@master
    with:
      bazel: rolling
      name: macos_rolling_head_deps
      shell_commands: .bazelci/update_workspace_to_deps_heads.sh
